### PR TITLE
63 comparative chart

### PR DESCRIPTION
**Pull request by allthesignals**
Style and functionality implementation for comparative charts.

Introduces new components:
ranking-chart:
c3 was too heavy for our purposes, so we re-use land-use-chart component here to create a ranking-chart. This chart component takes the follow params:
 - data: an array of objects requiring two key-value pairs: any named property containing a numeric value, and a “borocd” value.
 - column: a string specifying which property in the data objects should be used

key-indicators:
This component creates a wrapping “key indicators” which allows multiple “key indicator” components. These child components should be used as contextual components because they share a lot of the same configuration as the parent, including information about columns.

Please take a look - more detail in specific commit messages.

### CODE REVIEW

**Comment by andycochran** [comment]
I'll take a look…

**Comment by andycochran** [comment]
The `svg.chart` could be taller. Maybe 100px instead of 50px?

**Comment by andycochran** [comment]
Width needs to be auto. When resizing the window, the chart's size doesn't change responsively. So it can stick out the side of the container or be too small. 

image

image

**Comment by andycochran** [comment]
Change `.tooltip` padding to `padding: 5px 10px;`.  Needs more on the sides.

**Comment by andycochran** [comment]
Align the center of tooltip with the hovered bar. Add `margin-left: [toolip width / 2];` to the `.tooltip`.

**Comment by andycochran** [comment]
Show current District's tooltip when not hovering the chart. This way the chart is useful w/o interaction.

**Comment by allthesignals** [comment]
Thanks, @andycochran 

 - [ ] Show current District's tooltip when not hovering the chart. This way the chart is useful w/o interaction.
 - [ ] Align the center of tooltip with the hovered bar. Add margin-left: [toolip width / 2]; to the .tooltip.
 - [ ] Change .tooltip padding to padding: 5px 10px;. Needs more on the sides.
 - [ ] Width needs to be auto. When resizing the window, the chart's size doesn't change responsively. So it can stick out the side of the container or be too small. 
image
image
 - [ ] The svg.chart could be taller. Maybe 100px instead of 50px?
 - [ ] I'll take a look…

**Comment by allthesignals** [comment]
"Width needs to be auto. When resizing the window, the chart's size doesn't change responsively. So it can stick out the side of the container or be too small."

Holding off on this, it's a little bigger of a lift.

There isn't yet a hover-over highlight yet - there's some unpredictability due to the route transitions and how the "rank" gets delegated to the chart. Because rank is referenced in the d3 callbacks, I'm afraid there are some weird race conditions going on, will need to investigate further...

**Pull request merged**
