### PR TITLE
Fix highlight bug

### LINKED ISSUE #329: Blue bars in Resiliency Ranking Charts aren't responsive
image

### LINKED ISSUE #330: Highlighted CD in Resiliency Ranking Charts
The currently selected/hovered district in the Resiliency charts should change color of blue bar, not the grey bar. As-is it has the effect of making the district look to be more in the floodplain than it actually is. 

image

### PR DESCRIPTION
**Pull request by allthesignals**
Refactor ranking-chart; extend it appropriately, renaming; remove ranking-chart-plus component for resiliency-chart; better naming;

Closes #330 

Also closes #329

### CODE REVIEW

**Comment by andycochran** [comment]
This clobbers the work that colors the grey/blue bars with more contrast in the floodplain maps. 

image

image

The default grey and MOE color should be different than the floodplain's grey and blue. The floodplain chart's grey was lightened significantly and its blue darkened to create more contrast. Whereas the default charts use a transparent blue that appears darker over the bar and lighter over the white background.

**Comment by allthesignals** [comment]
@andycochran so it should be the lighter gray used for the resiliency charts? And the darker gray for the indicator charts? Are these colors specified in CSS somewhere? Did not intend to clobber the color work - I needed to refactor the base chart class so the highlighting logic would work, and it might've gotten lost, possibly due to the fact that some CSS class names changed (I have the colors stored as hash in the class, maybe I thought those were the right ones). Let me know, thanks.

**Comment by andycochran** [comment]
I'd defined the colors in the JS. You can ee what they should be on the `develop` branch.

**Comment by andycochran** [comment]
Regular charts: 
- #a8a8a8
- #6eceff 

Resiliency charts
- #dddddd
- #60acbf

**Pull request merged**
