### PR TITLE
Section/Layout Overhaul

### LINKED ISSUE #119: Community District Header does not float
When scrolling down, CD header does not float but disappears with page.

### LINKED ISSUE #153: Indicator Chart Tooltip Z-index issue
It floats above the sticky nav

### LINKED ISSUE #156: Main content leaves side-scrollable margin on window resize
When the window is made smaller than on first load, the main content area becomes side-scrollable, with a margin the width of the area that the window was reduced by.  @andycochran believes this is linked to the sticky nav.

### PR DESCRIPTION
**Pull request by andycochran**
This PR overhauls the page layout. 
- removes `.grid-container` elements on CD profiles so that the content fills the entire width of large screens
- adds a new two-column layout for key indicators with slimmer ranking charts (gets more stats on the page at a time)
- adjusts typography sizes for better hierarchy 
- reduces the font size of big stats
- better styles for the boro/city comparative stats
- slightly reduces the size of the map on xlarge screens
- cleans up Sass
- uses fixed positioning to make the site header, map, typeahead sticky on large screens (closes #156)… without the sticky plugin which was removed (closes #153)
- makes district header sticky on large screens (closes #119) 
- fixes momentum-based scrolling on touch devices

### CODE REVIEW

**Comment by allthesignals** [comment]
This looks great - I think the scroll-tos are unfortunately broken now, we'll have to look into it together.

**Comment by allthesignals** [comment]
Alright, I pushed a fix to this branch, @andycochran - it was something to do with how the scroller service was selecting it's scroll context. Anyway, we need to work on the offset for that - but this otherwise looks great 😁

**Comment by andycochran** [comment]
Cool. I've fixed the merge conflicts.

**Comment by andycochran** [comment]
Looks like offset is an issue in the plugin. https://github.com/ragnarpeterson/ember-scroll-to/issues/12

**Comment by allthesignals** [comment]
@andycochran it's not the plugin, the offset option works in the plugin (I think that issue is 2 years old, and it's closed, so they probably fixed whatever the issue was then). I'm working on finding the right offset for the new fixed header. Thanks!

**Pull request merged**
